### ISSUE TITLE
Where can I download the paper？

### ISSUE THREAD

**Issue by kbzhang** [natalieparde/metaphor-novelty-scoring#1]
Hi, I can't find a place to down the paper from google , can you give me a link to down the paper first? thx

**Comment by natalieparde** [comment]
Hi kbzhang,

Sure!  The paper can be found here (it'll also be in the AAAI Digital Library once this year's conference proceedings are released): http://natalieparde.com/papers/aaai18_parde_camera_ready.pdf

Let me know if you have any questions about the paper or about the code/data that we released.

-Natalie
